name: Deploy to Amazon ECS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: common_assessment_tool
  ECS_CLUSTER: CommonAssessmentTool_Cluster
  ECS_SERVICE: CommonAssessmentTool_Service
  TASK_DEFINITION_NAME: CommonAssessmentTool_Deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Get AWS Account ID
      id: get-account-id
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        echo "ACCOUNT_ID=${ACCOUNT_ID}" >> $GITHUB_ENV

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Extract short SHA
      id: vars
      run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        IMAGE_URI=${ACCOUNT_ID}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${SHA_SHORT}
        echo "IMAGE_URI=${IMAGE_URI}" >> $GITHUB_ENV
        docker build -t ${IMAGE_URI} .
        docker push ${IMAGE_URI}

    - name: Get current task definition
      run: |
        aws ecs describe-task-definition \
          --task-definition ${{ env.TASK_DEFINITION_NAME }} \
          --query taskDefinition \
          --output json > task-def.json

    - name: Clean and update task definition JSON
      run: |
        jq 'del(
          .taskDefinitionArn,
          .revision,
          .status,
          .requiresAttributes,
          .compatibilities,
          .registeredAt,
          .registeredBy,
          .taskDefinitionStatus
        ) | 
        (.containerDefinitions[0].image) = "'"${IMAGE_URI}"'"' task-def.json > new-task-def.json

    - name: Register new task definition
      run: |
        NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
          --cli-input-json file://new-task-def.json \
          --query 'taskDefinition.taskDefinitionArn' \
          --output text)
        echo "TASK_DEF_ARN=${NEW_TASK_DEF_ARN}" >> $GITHUB_ENV

    - name: Update ECS service
      run: |
        aws ecs update-service \
          --cluster ${{ env.ECS_CLUSTER }} \
          --service ${{ env.ECS_SERVICE }} \
          --task-definition ${TASK_DEF_ARN} \
          --force-new-deployment