name: Deploy to Amazon ECS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2
      ECR_REPOSITORY: common_assessment_tool
      ECS_CLUSTER: your-ecs-cluster-name
      ECS_SERVICE: your-ecs-service-name
      TASK_DEFINITION_NAME: CommonAssessmentTool_Deployment

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to ECR
      run: |
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Download task definition
      run: |
        aws ecs describe-task-definition \
          --task-definition $TASK_DEFINITION_NAME \
          --query taskDefinition \
          --output json > task-def.json

    - name: Update task definition with new image
      run: |
        sed -i "s|image\": \".*\"|image\": \"${IMAGE_URI}\"|" task-def.json
        sed -i '/taskDefinitionArn/d' task-def.json
        sed -i '/revision/d' task-def.json
        sed -i '/status/d' task-def.json
        sed -i '/requiresAttributes/d' task-def.json
        sed -i '/compatibilities/d' task-def.json
        sed -i '/registeredAt/d' task-def.json
        sed -i '/registeredBy/d' task-def.json

    - name: Register new task definition
      id: register-task-def
      run: |
        NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
          --cli-input-json file://task-def.json \
          --query 'taskDefinition.taskDefinitionArn' \
          --output text)
        echo "TASK_DEF_ARN=$NEW_TASK_DEF_ARN" >> $GITHUB_ENV

    - name: Deploy updated task definition to ECS service
      run: |
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --task-definition $TASK_DEF_ARN
